type IconTypes =
  | 'About'
  | 'Badge'
  | 'Cart'
  | 'ChevronLeft'
  | 'ChevronRight'
  | 'Close'
  | 'Comment'
  | 'DownArrow'
  | 'Facebook'
  | 'FacebookCircle'
  | 'Factory'
  | 'FactoryWindow'
  | 'HamburgerNav'
  | 'Home'
  | 'Instagram'
  | 'Phone'
  | 'Pinterest'
  | 'Play'
  | 'Products'
  | 'Quote'
  | 'Star'
  | 'Twitter'
  | 'Youtube'

export type { IconTypes }
